---
- name: "[terminal]: Import omz tasks"
  import_tasks: omz.yml
  tags: terminal

- name: "[terminal]: Import iterm2 tasks"
  import_tasks: iterm2.yml
  tags: terminal

- name: "[terminal]: clone bash-insulter"
  git:
    repo: https://github.com/hkbakke/bash-insulter.git
    dest: "{{ config_dir }}/bash-insulter"
    version: master
    update: true
  become: true
  tags: terminal

- name: "[terminal]: install bash-insulter"
  ansible.builtin.copy:
    src: "{{ config_dir }}/bash-insulter/src/bash.command-not-found"
    dest: /etc/
  become: true
  tags: terminal
