---
rtx_user: "{{ ansible_user_id }}"
rtx_group: "{{ ansible_user_gid }}"
rtx_dir: "{{ ansible_user_id }}/.local/share/rtx"

shells_to_activate:
  - zsh
  - bash
  - fish
# by default, no plugins and apps installed, you have to pass vars to role like this
# rtx_plugins:
#   - name: erlang
#     repository: ""
#     versions:
#       - 20.1
#     delete_versions: []
#     global: 20.1
rtx_plugins: []
