---
- name: "Check if fonts are already installed"
  command: ls /Users/{{ ansible_user_id }}/Library/Fonts/
  register: current_fonts
  when: false

- name: "[Fonts]: Set fonts variable"
  set_fact:
    fonts:
      - name: FiraCode
        archive: https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip
        directory: ttf
        files:
          - FiraCode-Bold.ttf
          - FiraCode-Light.ttf
          - FiraCode-Medium.ttf
          - FiraCode-Regular.ttf
          - FiraCode-Retina.ttf
      - name: Monoid
        archive: https://github.com/JB-Dmitry/monoid/blob/master/Monoid-0.61-with-IntelliJ-support.zip?raw=true
        directory: ""
        files:
          - Monoisome-Regular.ttf
          - Monoid-Retina.ttf
          - Monoid-Bold.ttf
          - Monoid-Italic.ttf
  when: fonts is undefined

- name: "[Fonts]: Create a directory if it does not exist"
  ansible.builtin.file:
    path: "/tmp/fonts-{{ item.name }}"
    state: directory
    mode: "0755"
  loop: "{{ fonts }}"
  when: current_fonts == ""

- name: "[Fonts]: Download and Extract font files"
  unarchive:
    src: "{{ item.archive }}"
    dest: "/tmp/fonts-{{ item.name }}"
    remote_src: true
  loop: "{{ fonts }}"
  when: current_fonts == ""

- name: "[Fonts]: Install fonts from repositories"
  copy:
    src: "/tmp/fonts-{{ item.0.name }}/{{ item.0.directory }}/{{ item.1 }}"
    dest: "/Users/{{ ansible_user_id }}/Library/Fonts/{{ item.1 }}"
  loop: "{{ fonts | subelements('files') }}"
  when: current_fonts == ""

- name: "[Fonts]: Remove repositories"
  file:
    path: "/tmp/fonts-{{ item.name }}"
    state: absent
  changed_when: false
  loop: "{{ fonts }}"
  when: current_fonts == ""
