---
- name: Download and install kitty
  ansible.builtin.command: "curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin"
  changed_when: false

- name: Create symbolic links to add kitty and kitten to PATH
  ansible.builtin.command: "ln -sf ~/.local/kitty.app/bin/kitty ~/.local/kitty.app/bin/kitten ~/.local/bin/"
  changed_when: false

- name: Place the kitty.desktop file somewhere it can be found by the OS
  ansible.builtin.command: "cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/"
  changed_when: false

- name: If you want to open text files and images in kitty via your file manager also add the kitty-open.desktop file
  ansible.builtin.command: "cp ~/.local/kitty.app/share/applications/kitty-open.desktop ~/.local/share/applications/"
  changed_when: false

- name: Update the paths to the kitty and its icon in the kitty.desktop file(s)
  ansible.builtin.command: 'sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop'
  changed_when: false

- name: If you want to open text files and images in kitty via your file manager also add the kitty-open.desktop file
  ansible.builtin.command: 'sed -i "s|Exec=kitty|Exec=/home/$USER/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop'
  changed_when: false
