---
username: hest

password: changeme

shell: /bin/zsh

packages:
  - curl
  - diff-so-fancy
  - docker
  - jq
  - nvim
  - bitwarden
  - firefox
  - slack
  - insomnia
  - postman

classics:
  - chezmoi
  - kubectl
  - code
