---
- name: "Install Homebrew"
  include_tasks: "yabai.yml"
  when: "install_homebrew is defined and install_homebrew == true"

- name: "Install Homebrew packages."
  include_tasks: "skhd.yml"
  when: "install_packages is defined and install_packages == true"
