---
- name: Block
  become: true
  block:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: true

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true

    - name: Create directory ~/.local/bin
      file:
        path: ~/.local/bin
        state: directory
        mode: "0755"

    - name: Create symlink for batcat
      file:
        src: /usr/bin/batcat
        dest: ~/.local/bin/bat
        state: link
