---
- name: Add the universe repository
  ansible.builtin.apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
    state: present
    update_cache: yes
  become: true

- name: Update repositories cache and install fonts
  ansible.builtin.apt:
    name: fonts-firacode
    update_cache: yes
  become: true
