---
- name: "[yabai]: verify skhd is installed"
  community.general.homebrew:
    name: skhd
    state: present
  register: skhd_installed
  until: skhd_installed is succeeded
  tags:
    - yabai

- name: "[yabai]:check if skhd is installed already"
  stat:
    path: "/Users/{{ ansible_user_id }}/Library/LaunchAgents/com.koekeishiya.skhd.plist"
  register: skhd_service

- name: "[yabai]: install brew service skhd"
  command: skhd --install-service
  changed_when: false
  when: not skhd_service.stat.exists
  tags:
    - yabai

- name: "[yabai]: start brew service skhd"
  command: skhd --start-service
  changed_when: false
  tags:
    - yabai
