---
- name: "[yabai]: verify yabai is installed"
  community.general.homebrew:
    name: yabai
    state: present
  register: yabai_installed
  until: yabai_installed is succeeded
  tags:
    - yabai

- name: "[yabai]: configure scripting addition"
  ansible.builtin.lineinfile:
    dest: /private/etc/sudoers.d/yabai
    line: "{{ ansible_user_id }} ALL = (root) NOPASSWD: /usr/local/bin/yabai --load-sa"
    validate: "/usr/sbin/visudo -cf %s"
    create: true
  become: true
  tags:
    - yabai

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /Users/{{ ansible_user_id }}/Library/LaunchAgents
    state: directory
    mode: "0755"

- name: "[yabai]: install the yabai service"
  command: yabai --install-service
  changed_when: false
  tags:
    - yabai

- name: "[yabai]: start the yabai service"
  command: yabai --start-service
  changed_when: false
  tags:
    - yabai
