---
- name: Install packages
  ansible.builtin.package:
    name:
      - git
      - node-typescript
      - make
    state: present
  become: true

- name: Clone the Git repository
  ansible.builtin.git:
    repo: https://github.com/pop-os/shell
    dest: /home/{{ ansible_user_id }}/shell
    version: 1.2.0

- name: Run Make on pop shell
  community.general.make:
    chdir: /home/{{ ansible_user_id }}/shell
    target: install
# sudo apt install git node-typescript make
# git clone https ://github.com/pop-os/shell
# make local-install
