---
- name: Install packages
  ansible.builtin.package:
    name:
      - git
      - node-typescript
      - make
    state: present
  become: true

- name: Clone the Git repository
  ansible.builtin.git:
    repo: https://github.com/pop-os/shell
    dest: /home/{{ ansible_user_id }}/shell
    version: 1.2.0

- name: Initialize dotfiles repo
  ansible.builtin.command: "cd /home/{{ ansible_user_id }}/shell"
  changed_when: false

- name: Make install pop shell
  ansible.builtin.command:
    cmd: make local-install
  changed_when: false
# sudo apt install git node-typescript make
# git clone https ://github.com/pop-os/shell
# make local-install
