---
- name: Install packages (shell)
  ansible.builtin.package:
    name:
      - git
      - node-typescript
      - make
    state: present
  become: true

- name: Clone the Git repository (shell)
  ansible.builtin.git:
    repo: https://github.com/pop-os/shell
    dest: /home/{{ ansible_user_id }}/shell
    version: 1.2.0

- name: Run Make (shell)
  community.general.make:
    chdir: /home/{{ ansible_user_id }}/shell
    target: local-install

- name: Install packages (shell-shortcuts)
  ansible.builtin.package:
    name:
      - cargo
      - rustc
      - libgtk-3-dev
    state: present
  become: true

- name: Clone the Git repository (shell-shortcuts)
  ansible.builtin.git:
    repo: https://github.com/pop-os/shell-shortcuts
    dest: /home/{{ ansible_user_id }}/shell-shortcuts

- name: Run Make (shell-shortcuts)
  community.general.make:
    chdir: /home/{{ ansible_user_id }}/shell-shortcuts
    target: install
  become: true
