---
- name: Install dependencies with Homebrew
  homebrew:
    name: "{{ asdf_dependencies }}"
  when: ansible_os_family == "Darwin"

- name: Install dependencies with Homebrew
  homebrew:
    name: "{{ asdf_plugin_dependencies }}"
  when: ansible_os_family == "Darwin"

- name: "Install asdf plugins"
  shell: >-
    . {{ asdf_dir }}/asdf.sh &&
    asdf plugin-add {{ item.name }} {{ item.repository | default() }}
  args:
    executable: "{{ asdf_install_shell | default(omit) }}"
    creates: "{{ asdf_dir }}/plugins/{{ item.name }}"
    chdir: "{{ asdf_home }}"
  with_items: "{{ asdf_plugins }}"
  ignore_errors: True

- name: "Install asdf packages"
  shell: >-
    . {{ asdf_dir }}/asdf.sh &&
    asdf install {{ item.0.name }} {{ item.1 }}
  args:
    executable: "{{ asdf_install_shell | default(omit) }}"
    creates: "{{ asdf_dir }}/installs/{{ item.0.name }}/{{ item.1 }}"
    chdir: "{{ asdf_home }}"
  with_subelements:
    - "{{ asdf_plugins }}"
    - versions
    - flags:
      skip_missing: True
