---
- name: Bootstrap OSX dev machine
  hosts: all

  vars:
    homebrew_use_brewfile: false
    homebrew_taps:
      - koekeishiya/formulae
    homebrew_installed_packages:
      - yabai
    homebrew_cask_apps:
      - visual-studio-code
    rtx_plugins:
      - name: golang
        versions:
          - latest 
        global: latest 
      - name: java
        versions:
          - 17
          - 20
        global: 20
      - name: rust
        versions:
          - latest
        global: latest 
      - name: python
        repository: "https://github.com/asdf-community/asdf-python.git"
        versions:
          - 3.11.4
        global: 3.11.4

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]

    - role: hesthub.ansible_rtx
      tags: ["rtx"]

    - role: names
      tags: ["names"]

    - role: fonts
      tags: ["fonts"]

    - role: dotfiles
      vars:
        github_name: "hest-hub"
      tags: ["dotfiles"]

    - role: terminal
      tags: ["terminal"]

    - role: vscode
      tags: ["vscode"]

    - role: jetbrains
      tags: ["jetbrains"]

    - role: yabai
      tags: ["yabai"]

    - role: macos-defaults
      tags: ["macos-defaults"]

    - role: brewfile
      tags: ["brewfile"]
