---
- name: Bootstrap OSX dev machine
  hosts: all


  vars:
    homebrew_use_brewfile: false
    homebrew_taps:
      - koekeishiya/formulae
    homebrew_installed_packages:
      - yabai
    homebrew_cask_apps:
      - visual-studio-code
  roles:
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]

    - role: names
      tags: ["names"]

    - role: fonts
      tags: ["fonts"]

    - role: dotfiles
      vars:
        github_name: "hest-hub"
      tags: ["dotfiles"]

    - role: terminal
      tags: ["terminal"]

    - role: vscode
      tags: ["vscode"]

    - role: jetbrains
      tags: ["jetbrains"]

    - role: yabai
      tags: ["yabai"]

    - role: macos-defaults
      tags: ["macos-defaults"]

    - role: brewfile
      tags: ["brewfile"]
