---
- name: Bootstrap OSX dev machine
  hosts: all


  vars:
    homebrew_use_brewfile: false
    homebrew_taps:
      - koekeishiya/formulae
    homebrew_installed_packages:
      - yabai
    homebrew_cask_apps:
      - visual-studio-code
    rtx_plugins:
      - name: golang 
        repository: ""
        versions:
          - 1.20.1
        delete_versions: []
        global: 1.20.1
      - name: java 
        repository: ""
        versions:
          - 20
        delete_versions: []
        global: 20
      - name: nodejs 
        repository: "https://github.com/asdf-vm/asdf-nodejs.git"
        versions:
          - 20.4.0
        delete_versions: []
        global: 20.4.0
      - name: python 
        repository: "https://github.com/asdf-community/asdf-python.git"
        versions:
          - 3.6.12
        delete_versions: []
        global: 3.6.12
  roles:
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]

    - role: rtx
      tags: ["rtx"]

    - role: names
      tags: ["names"]

    - role: fonts
      tags: ["fonts"]

    - role: dotfiles
      vars:
        github_name: "hest-hub"
      tags: ["dotfiles"]

    - role: terminal
      tags: ["terminal"]

    - role: vscode
      tags: ["vscode"]

    - role: jetbrains
      tags: ["jetbrains"]

    - role: yabai
      tags: ["yabai"]

    - role: macos-defaults
      tags: ["macos-defaults"]

    - role: brewfile
      tags: ["brewfile"]
