---
- name: Bootstrap OSX dev machine
  hosts: all

  vars_files:
    - default.config.yml
  tasks:
    - name: Dotfiles
      import_tasks: tasks/dotfiles.yml
      tags: ["dotfiles"]
    - name: Fonts
      import_tasks: tasks/fonts.yml
      tags: ["Fonts"]
