---
# Brew install stable
- community.general.homebrew:
    name: rtx
    state: present

- name: Update zshrc
  ansible.builtin.lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    create: true
    mode: "0644"
    line: eval "$(rtx activate zsh)"
    regexp: ^eval "$(rtx activate zsh)"

- name: Source zshrc
  ansible.builtin.shell: source {{ lookup('env', 'HOME') }}/.zshrc && echo bashrc sourced
  args:
    executable: /bin/bash
  changed_when: false
