---
# Brew install stable
- name: "Install via Brew"
  community.general.homebrew:
    name: rtx
    state: present

- name: zsh
  block:
    - name: Update zshrc
      ansible.builtin.lineinfile:
        dest: "{{ lookup('env', 'HOME') }}/.zshrc"
        create: true
        mode: "0644"
        line: eval "$(rtx activate zsh)"
        regexp: ^eval "$(rtx activate zsh)"

    - name: Source zshrc
      ansible.builtin.shell: source {{ lookup('env', 'HOME') }}/.zshrc && echo zshrc sourced
      args:
        executable: /usr/local/bin/zsh
      changed_when: false
  when: "'zsh' in shells_to_activate"

- name: bash
  block:
    - name: Update bashrc
      ansible.builtin.lineinfile:
        dest: "{{ lookup('env', 'HOME') }}/.bashrc"
        create: true
        mode: "0644"
        line: eval "$(rtx activate bash)"
        regexp: ^eval "$(rtx activate bash)"

    - name: Source bashrc
      ansible.builtin.shell: source {{ lookup('env', 'HOME') }}/.bashrc && echo bashrc sourced
      args:
        executable: /bin/bash
      changed_when: false
  when: "'bash' in shells_to_activate"

- name: fish
  block:
    - name: Update fish config
      ansible.builtin.lineinfile:
        dest: "{{ lookup('env', 'HOME') }}/.config/fish/config.fish"
        create: true
        mode: "0644"
        line: "rtx activate fish"
        regexp: "^rtx activate fish"

  when: "'fish' in shells_to_activate"
