---
# tasks file for rtx

- name: "Extract name into a list and register variable plugins_to_install from vars: rtx_plugins"
  ansible.builtin.set_fact:
    plugins_to_install: "{{ rtx_plugins | map(attribute='name') | list }}"
