---
- name: Bootstrap linux dev machine
  hosts: all

  roles:
    - role: apt
    - role: snap
    - role: dotfiles
    - role: diodonfrost.jetbrains_toolbox
    - role: terminal
    #- role: chriscroome.kitty 